### ISSUE TITLE
Error authenticating! Error: Token provided to verifyJWT is missing or not a string ?

### ISSUE THREAD

**Issue by kilaniba** [feathersjs/feathers-authentication#584] opened 2017-10-10 08:23 UTC
I work with reactjs frontend. After create my server.js (feathers ) , i try to send my (username and password) to my route post . there is my code .

```js
axios.post('http://localhost:4200/login', {
  strategy: 'local',
  username: 'k0',//self.state.username, password:'kk'//
  self.state.password
}).then(response => {
  console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken);
}).then(payload => {
  console.log('JWT Payload', payload);
  return app.service('users').get(payload.userId);
}).then(user => {
  app.set('user', user);
  console.log('User', app.get('user'));
}).catch(function(error) {
  console.error('Error authenticating!', error);
});
```

When i click my button , there is my error in console "Error authenticating! Error: Token provided to verifyJWT is missing or not a string".

**Comment by daffl** [comment] 2017-10-10 15:03
What is the `/login` route? What versions are you using? Unless you share your complete setup (which does not seem to be the standard generator structure) there unfortunately is not much we can do to help.

**Comment by kilaniba** [comment] 2017-10-10 15:15
This is my route post where i will verify authenticate . I feel i did an big mistake 
`app.post('/login', auth.express.authenticate('local', { successRedirect: '/app', failureRedirect: '/login' }));`

**Comment by daffl** [comment] 2017-10-10 15:29
I meant the entire application setup. The minimum complete amount of code we need to reproduce your issue.

**Comment by kilaniba** [comment] 2017-10-10 15:36
server.js
`var Users=[
{_id:"1",email:"k0",password:"kk"},
{_id:"2",email:"k1",password:"kk"},
{_id:"3",email:"k2",password:"kk"},
{_id:"4",email:"k3",password:"kk"},
{_id:"5",email:"k4",password:"kk"}];
const feathers = require('feathers');
const bodyParser = require('body-parser');
const errors = require('feathers-errors');
const errorHandler = require('feathers-errors/handler');
const rest = require('feathers-rest');
const hooks = require('feathers-hooks');
const auth = require('feathers-authentication');
const local = require('feathers-authentication-local');
const memory = require('feathers-memory');
const jwt = require('feathers-authentication-jwt');
const app = feathers();
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }));
var cors = require('cors');
var port= process.env.PORT || 4200;
app.use(cors());
app.configure(rest())
.configure(hooks())
.use(bodyParser.json())
.use(bodyParser.urlencoded({ extended: true }))
.configure(auth({ secret: 'supersecret' }))
.configure(jwt())
.configure(local())
//.use('/users', memory());
.use('/users', {
   find(params) {
     return Promise.resolve(Users);
   }
 })
 .use(errorHandler());
app.service('authentication').hooks({
  before: {
    create: [
      auth.hooks.authenticate('local'),
      customizeJWTPayload()
    ],
    remove: [
      auth.hooks.authenticate('jwt')
    ]
  }
  });
  app.service('users').hooks({
  before: {

    create: [
      local.hooks.hashPassword({ passwordField: 'password' })
    ]
  }
});
  /////////////////
  app.post('/login', auth.express.authenticate('local', { successRedirect: '/app', failureRedirect: '/login' }));

  app.get('/app', (req, res, next) => {
  res.json({ success: true });
  });

  app.get('/login', (req, res, next) => {
  res.json({ success: "faux" });
  });
app.listen(port);`

**Comment by kilaniba** [comment] 2017-10-10 15:46
@daffl the error in the route `/login` ?

**Comment by kilaniba** [comment] 2017-10-10 16:07
in login.js

`const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const hooks = require('feathers-hooks');
const localStorage = require('localstorage-memory');
//const jwt = require('feathers-authentication-jwt');
const auth = require('feathers-authentication-client');
const restClient = rest();
const app = feathers();
const axios = require('axios');
//app.configure(restClient.axios(axios))
app.configure(hooks())
   .configure(rest('http://localhost:4200').axios(axios))
   .configure(auth({ storage: localStorage }));
  app.authenticate({
    strategy: 'local',
    username: 'k0',//self.state.username,
    password:'kk'// self.state.password
  })
  .then(response => {
    console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken /*feathers-jwt*/);
})
.then(payload => {
  console.log('JWT Payload', payload);
  return app.service('users').get(payload.userId);
})
.then(user => {
  app.set('user', user);
  console.log('User', app.get('user'));
})
.catch(function(error){
  console.error('Error authenticating!', error);
})`

**Comment by kilaniba** [comment] 2017-10-10 16:10
in my login.js
`const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const hooks = require('feathers-hooks');
const localStorage = require('localstorage-memory');
//const jwt = require('feathers-authentication-jwt');
const auth = require('feathers-authentication-client');
const restClient = rest();
const app = feathers();
const axios = require('axios');
//app.configure(restClient.axios(axios))
app.configure(hooks())
   .configure(rest('http://localhost:4200').axios(axios))
   .configure(auth({ storage: localStorage }));
axios.post('http://localhost:4200/login', {
  strategy: 'local',
  username: 'k0',
 password:'kk'
  self.state.password
}).then(response => {
  console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken);
}).then(payload => {
  console.log('JWT Payload', payload);
  return app.service('users').get(payload.userId);
}).then(user => {
  app.set('user', user);
  console.log('User', app.get('user'));
}).catch(function(error) {
  console.error('Error authenticating!', error);
});`

**Comment by bertho-zero** [comment] 2017-10-10 17:53
You can put your code between \``` to make it clearer, if you wish.

**Comment by kilaniba** [comment] 2017-10-10 17:59
@bertho-zero 
`var Users=[
{_id:"1",email:"k0",password:"kk"},
{_id:"2",email:"k1",password:"kk"},
{_id:"3",email:"k2",password:"kk"},
{_id:"4",email:"k3",password:"kk"},
{_id:"5",email:"k4",password:"kk"}];
const feathers = require('feathers');
const bodyParser = require('body-parser');
const errors = require('feathers-errors');
const errorHandler = require('feathers-errors/handler');
const rest = require('feathers-rest');
const hooks = require('feathers-hooks');
const auth = require('feathers-authentication');
const local = require('feathers-authentication-local');
const memory = require('feathers-memory');
const jwt = require('feathers-authentication-jwt');
const app = feathers();
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }));
var cors = require('cors');
var port= process.env.PORT || `4200;app.use(cors());
app.configure(rest())
.configure(hooks())
.use(bodyParser.json())
.use(bodyParser.urlencoded({ extended: true }))
.configure(auth({ secret: 'supersecret' }))
.configure(jwt())
.configure(local())
//.use('/users', memory());
.use('/users', {
find(params) {
return Promise.resolve(Users);
}
})
.use(errorHandler());
app.service('authentication').hooks({
before: {
create: [
auth.hooks.authenticate('local'),
customizeJWTPayload()
],
remove: [
auth.hooks.authenticate('jwt')
]
}
});
app.service('users').hooks({
before: {

create: [
  local.hooks.hashPassword({ passwordField: 'password' })
]
}
`});app.post('/login', auth.express.authenticate('local', { successRedirect: '/app', failureRedirect: '/login' }));

app.get('/app', (req, res, next) => {
res.json({ success: true });
});

app.get('/login', (req, res, next) => {
res.json({ success: "faux" });
});
app.listen(port);````

**Comment by daffl** [comment] 2017-10-15 03:21
Going to close this since I think we solved it in https://github.com/feathersjs/feathers-authentication-local/issues/36

**Closed by daffl** 2017-10-15 03:21 UTC
