### ISSUE TITLE
hook.params.user

### ISSUE THREAD

**Issue by marcpaskell** [feathersjs/feathers-authentication#483] opened 2017-04-13 12:57 UTC
It would appear that (via socket.io) once authenticated the user object isnt updated on the hooks.params until a full refresh/re-auth?

**Comment by ekryski** [comment] 2017-04-13 15:43
Thanks! Yup, duplicate of #293

**Closed by ekryski** 2017-04-13 15:43 UTC

**Comment by marcpaskell** [comment] 2017-04-14 07:05
Thanks @ekryski - any idea when #293 will be ready?

**Comment by marshallswain** [comment] 2017-04-14 12:09
@marcpaskell We're closing out a release, currently.  This will come as a patch release.  We have some prioritizing to do, but this is pretty important.
