### ISSUE TITLE
"username" cannot be used as local strategy usernameField

### ISSUE THREAD

**Issue by Creiger** [feathersjs/feathers-authentication#294] opened 2016-09-22 13:37 UTC
When i override local strategy settings with "usernameField" : "username", it does not work. If i use any other fieldname, it works. Is this some restriction?

**Comment by marshallswain** [comment] 2016-09-24 23:08
@Creiger not that I know of.  Have you done any debugging to figure out the cause?   If you can publish a repo with a breaking example we could be more helpful.

**Comment by sean-nicholas** [comment] 2016-10-03 20:17
Same here. When I'm calling app.get('auth') it looks like this:

```json
{
    "local": {
        "usernameField": "Sean"
    }
}
```

It seems my config "usernameField": "username" is getting replaced by my computer username

**Comment by ekryski** [comment] 2016-10-03 20:46
Wat! Ok thanks for the hunting @sean-nicholas. It's an issue with feathers-config or something that should be guarded against on windows. @Creiger are you running on windows?

**Comment by Creiger** [comment] 2016-10-04 07:11
@ekryski Yes, i am also running on Windows.

**Comment by sean-nicholas** [comment] 2016-10-20 09:10
@Creiger There is actually a way to escape configs with ```\\``` and therefore feathers does not look them up in the environment
```
{
    "local": {
        "usernameField": "\\username"
    }
}
```

**Comment by daffl** [comment] 2016-10-20 14:25
I totally forgot about this! Thank you @sean-nicholas. It't is also documented [here](https://docs.feathersjs.com/configuration/readme.html):

> If the value starts with a \, do none of the above two

So I think we can close this.

**Closed by daffl** 2016-10-20 14:25 UTC
