### ISSUE TITLE
TypeError: Cannot read property 'service' of undefined

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-authentication#56] opened 2016-02-12 19:16 UTC
Hello,
I have made it to create user, but when logging in, I got no luck. [Code at gist](https://gist.github.com/wuyuanyi135/2a52b29f294bcded9991).

My request was
```
POST http://localhost:3000/auth/local
Content-Type: application/x-www-form-urlencoded

username=admin%40feathersjs.com&password=admin
```

It threw the exceptions:
```
TypeError: Cannot read property 'service' of undefined
    at Object.checkCredentials (/home/wuyuanyi/riddle-web/node_modules/feathers-authentication/lib/services/local/index.js:84:15)
    at Strategy.authenticate (/home/wuyuanyi/riddle-web/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/home/wuyuanyi/riddle-web/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/home/wuyuanyi/riddle-web/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at /home/wuyuanyi/riddle-web/node_modules/feathers-authentication/lib/services/local/index.js:141:9
    at new Promise (/home/wuyuanyi/riddle-web/node_modules/core-js/modules/es6.promise.js:197:7)
    at Object.create (/home/wuyuanyi/riddle-web/node_modules/feathers-authentication/lib/services/local/index.js:120:14)
    at Object.wrapper (/home/wuyuanyi/riddle-web/node_modules/feathers/lib/mixins/promise.js:6:28)
    at Object.<anonymous> (/home/wuyuanyi/riddle-web/node_modules/uberproto/lib/proto.js:30:17)
    at Object.wrapped (/home/wuyuanyi/riddle-web/node_modules/rubberduck/lib/rubberduck.js:63:19)
    at /home/wuyuanyi/riddle-web/node_modules/feathers-hooks/lib/before.js:49:20
    at new Promise (/home/wuyuanyi/riddle-web/node_modules/core-js/modules/es6.promise.js:197:7)
    at /home/wuyuanyi/riddle-web/node_modules/feathers-hooks/lib/before.js:36:18
    at run (/home/wuyuanyi/riddle-web/node_modules/core-js/modules/es6.promise.js:104:47)
    at /home/wuyuanyi/riddle-web/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/home/wuyuanyi/riddle-web/node_modules/core-js/modules/$.microtask.js:19:5)
```

But once I made some mistake, like `Content-Type: application/x-www-form-urle`, the rejecting json message was returned
```js
{
"name": "NotAuthenticated"
"message": "Invalid login."
"code": 401
"className": "not-authenticated"
"errors": {}
}
```

Could anyone reproduce this?

**Comment by marshallswain** [comment] 2016-02-12 19:23
You've mounted your user service at `/`, but you haven't let the auth plugin know about it.
```
app.use('/', service({Model: userModel}));
```

**Comment by wuyuanyi135** [comment] 2016-02-12 19:28
Should I set `userEndpoint: '/'` ?
I tried but I still got the same error messages

Thank you

**Comment by marshallswain** [comment] 2016-02-12 19:44
Yeah, the `userEndpoint` will need to match, but looking at that stack trace, that wasn't the problem that caused this.  (but it would have been the next one to come up:)  

That top line in the stack trace
```
at Object.checkCredentials (/home/wuyuanyi/riddle-web/node_modules/feathers-authentication/lib/services/local/index.js:84:15)
```
Is this:
```
this.app.service(this.options.userEndpoint).find(params).then(function (users) {
```

So for some reason this.app isn't set correctly in that service.

**Comment by marshallswain** [comment] 2016-02-12 19:49
I'd recommend trying to use the default userEndpoint, or setting it to something other than the root `/`.

**Comment by ekryski** [comment] 2016-02-12 19:49
Hmm. I'll look at that issue but ya you shouldn't be using the root '/' for a service. Services are meant to be descriptive anyway.

**Comment by wuyuanyi135** [comment] 2016-02-12 19:53
Thanks. I tried to use the default `/user`, still got the same problem.
I use feathers.use('api/user', [this module]) to route it so I use the root here. But it seems not the problem

**Comment by ekryski** [comment] 2016-02-12 19:56
if you are using `/api/user` for your endpoint the config value you pass for `userEndpoint` needs to match. So it would also need to be `/api/user`.

**Comment by ekryski** [comment] 2016-02-12 19:56
I'll try running your gist. See if there is something else going on.

**Comment by wuyuanyi135** [comment] 2016-02-12 20:00
@ekryski Thanks a lot :+1: 
Yeah I tried not to use `feathers.use` to route then it works. I assumed that the `userEndpoint` is relative to this `app`. I am trying if changing the endpoint will work

**Comment by ekryski** [comment] 2016-02-12 20:02
no problem. I think that may be your issue. Report back. We recently added some docs on routing. http://docs.feathersjs.com/middleware/routing.html

**Comment by wuyuanyi135** [comment] 2016-02-12 20:08
if I will post login request to `http://localhost:8080/riddle/api/user/auth/local`
my user end point is `http://localhost:8080/riddle/api/user/`

`index.js : app.use('/riddle/api',api);` -> `api: app.use('/user',user);` 
the user is the app in the gist, without listen(3000) but module.exports

What should the userEndPoint be?

**Comment by ekryski** [comment] 2016-02-12 20:23
@wuyuanyi135 ah ok you are mounting a sub-app. I haven't tried that with auth yet. I think `userEndpoint` should just be `/users` then or you could leave it blank as that is the default value.

**Comment by ekryski** [comment] 2016-02-12 20:28
Another thing I noticed in your gist is that all the hooks now take an `options` object. So you would change this:

```js
userService.before(
    {
        create: [authHooks.hashPassword('password')]
    }
)
```

to this:

```js
userService.before(
    {
        create: [authHooks.hashPassword({ passwordField: 'password'})]
    }
)
```

or you could just pass nothing since `password` is the default expected field.

**Comment by ekryski** [comment] 2016-02-12 20:48
@wuyuanyi135 I just pushed [a working sub-app example](https://github.com/feathersjs/feathers-authentication/tree/master/examples/sub-apps). Hopefully that helps.

**Comment by ekryski** [comment] 2016-02-12 20:49
I think the reason we were getting `this.app` undefined is because the sub app wasn't getting mounted properly. I'm going to close this now @wuyuanyi135 but if you aren't able to get the your stuff working after looking at the example we can create a new issue.

**Closed by ekryski** 2016-02-12 20:49 UTC

**Comment by wuyuanyi135** [comment] 2016-02-13 22:50
@ekryski  Thanks for your example. I have figured out the reason of this issue. It was improper configuration of the sub-apps. I left out these lines  in my `api` sub-app.
```js
var app = feathers()
.configure(socketio())
.configure(rest())
.use(bodyParser.json())
.use(bodyParser.urlencoded({extended: true}));
```

Even though there is no explicit use of feathers services, the intermediate router app:
```js
var feathers = require('feathers');
var app = feathers();

var user = require('./user');
app.use('/user',user);
```
won't work.

**Comment by ekryski** [comment] 2016-02-14 19:05
@wuyuanyi135 ya you are right. We should probably try and toss up some better error messaging or warnings. Thanks for that feedback!

The issue is actually related this one: https://github.com/feathersjs/feathers/issues/216. When we close that you shouldn't ever run into this problem.

**Comment by startupthekid** [comment] 2016-03-12 00:31
I've been having this issue for a few weeks too and it's super frustrating. My setup is relatively simple too:
```
const app = feathers();

app
  .configure(rest())
  .configure(hooks())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(authentication({
    token: {
      secret: config.JWT_SECRET
    },
    local: {
      usernameField: 'email'
    },
    facebook: {
      clientID: config.FACEBOOK_APP_ID,
      clientSecret: config.FACEBOOK_APP_SECRET,
      strategy: FacebookStrategy,
      tokenStrategy: FacebookTokenStrategy,
      permissions: {
        scope: ['email', 'public_profile']
      }
    }
  }))
  .use('/users', UserService)
  .use('/posts', PostService)
  .use('/groups', GroupService);
```

What's weird is that if I make a call to `/api/auth/local` (my sub-app is mounted at `/api`) using `x-www-form-urlencoded`, I get the `TypeError: Cannot read property &#39;service&#39; of undefined` error but if I change that to `form-data` (using Postman), then the error changes to `NotAuthenticated: Invalid login.`.

I did some more digging and in both cases, on the local setup, `setup` never gets called so that `this.app` is never set, which is why the call fails.

**Comment by wuyuanyi135** [comment] 2016-03-12 01:15
@startupthekid how did you configure the parent app?

**Comment by startupthekid** [comment] 2016-03-12 01:16
Very simply:

```
app
	.use('/api/', apiRoutes)
	.use(feathers.static(__dirname));
```

I believe I just found the error inside the local service but I'll need a few minutes to verify.

**Comment by startupthekid** [comment] 2016-03-12 01:23
Ok yeah I fixed it. @ekryski in the default export of the local service (and maybe others,I'm not sure):

```
export default function(options){
  options = Object.assign({}, defaults, options);
  debug('configuring local authentication service with options', options);

  return function() {
    const app = this;

    // Initialize our service with any options it requires
    app.use(options.localEndpoint, exposeConnectMiddleware, new Service(options), successfulLogin(options));

    // Get our initialize service to that we can bind hooks
    const localService = app.service(options.localEndpoint);

    // Register our local auth strategy and get it to use the passport callback function
    passport.use(new Strategy(options, localService.checkCredentials.bind(localService)));
  };
}
```

you have to add `localService.setup(app)`. I remember reading somewhere, one of the others feathers repos, that any service created from an ES6 class (using `new Service`), has to have `app.setup` called manually. When I added that line into the default export of the local service, I was able to login.

It had nothing to do with it being a sub-app as far as I can tell, everything to do with the service being an es6 based class.

**Comment by daffl** [comment] 2016-03-12 01:46
@startupthekid if you are using sub-apps, are you calling `app.setup(server)` as described [in the documentation](http://docs.feathersjs.com/middleware/mounting.html#subapps)?

**Comment by daffl** [comment] 2016-03-12 01:48
ES6 classes work the same way as normal services so that should not be an issue. But `service.setup` is called by `app.setup` which in your case probably never got called.

**Comment by startupthekid** [comment] 2016-03-12 02:18
Ah I see, the call to `app.setup` wasn't in the [example sub app that](https://github.com/feathersjs/feathers-authentication/tree/master/examples/sub-apps) @ekryski posted, that's where my confusion was coming from.

**Comment by daffl** [comment] 2016-03-12 04:04
It does call `setup` automatically if you use Socket.io but not without. There is no real reason for this except that I was being stupid ;)

https://github.com/feathersjs/feathers/issues/232 and https://github.com/feathersjs/feathers/issues/216 are probably related to this.

**Comment by ekryski** [comment] 2016-03-12 04:38
ok then we should probably call setup when rest is configured as well.

**Comment by thosakwe** [comment] 2016-03-17 20:16
Believe it or not, I'm having this problem too. And I don't have my API mounted as a subapp. I have no idea how to fix this, haha.

**Comment by ekryski** [comment] 2016-03-17 20:30
@thosakwe would you be able to post a link to your project somewhere? I'm wondering if it is related to https://github.com/feathersjs/feathers/issues/259.

**Comment by thosakwe** [comment] 2016-03-18 01:12
@ekryski I believe it is related to #259.

Here's the app.js:
https://gist.github.com/thosakwe/280e808bcc2175b273f1

I'm at a loss, though. I tried using app.listen in my bin/www (this was originally an Express app) file, but now the error is "data and hash arguments required." So something I did breaks bcrypt somewhere.

**Comment by ekryski** [comment] 2016-03-18 04:54
@thosakwe I need more than that to go on. The initial app setup looks just fine but I need to see how you set up your user service. If you don't have a user service set up, auth will not work. Additionally you need to make sure you are populating the user. Take a look at https://github.com/feathersjs/feathers-chat to see how those hooks are set up on the user service.

**Comment by daffl** [comment] 2016-03-18 06:04
@thosakwe Would you mind opening a new issue with the code for your app? That way it'll be much easier for us to keep track of instead of looking through the comments of a closed issue :) Thank you!

**Comment by thosakwe** [comment] 2016-03-18 13:44
Okay, cool. New issue: https://github.com/feathersjs/feathers-authentication/issues/108
