### ISSUE TITLE
Overriding JWT's expiresIn with a value more than 20d prevents users from signing in

### ISSUE THREAD

**Issue by johncrisostomo** [feathersjs/feathers-authentication#458] opened 2017-03-22 07:40 UTC
**UPDATE:** I forked this and tried running the tests locally, inspecting the tokens generated, and they seem to have a correct `exp` value. What gives?

I am trying to make a token expire a little longer than the default '1d', however, when I try a value greater than '20d', users are no longer able to sign in the app. I noticed that on the `utils.js` test cases, a value of '1y' was used but the token created was never 'asserted' to have a valid `exp` value.

I am aware that having a long enough token expiry is bad for security reasons, but I am just curious why this is not working properly.

**Comment by johncrisostomo** [comment] 2017-03-22 09:37
I re-opened this issue because I really want to know what's going on. Thank you in advance.

**Comment by ekryski** [comment] 2017-03-23 17:37
Hey @johncrisostomo,

I honestly have no idea. It **may** be something to do with the underlying [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) library that is being used. We're not doing anything to limit that and there isn't any issue or mention of a cap on the TTL of a JWT in the jsonwebtoken lib.

As you said, we don't recommend having tokens that long anyway but you might want to ask over on the [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) module if there is a limitation on the `expiresIn` field.

**Comment by jamesholcomb** [comment] 2017-03-23 17:54
@ekryski Are you recommending refresh token strategy in lieu of a long expiration token?

**Comment by marshallswain** [comment] 2017-03-23 18:12
@jamesholcomb there's no blanket recommendation, really.  It depends on each service's security requirements. Generally, using refresh tokens on a service will allow you to take advantage of JWT auth not requiring a round trip to the db.  Shorter expirations and using refresh tokens will probably be more secure than long expirations.

**Comment by jamesholcomb** [comment] 2017-03-23 18:18
I need to secure every service endpoint with a JWT and short expiration (1d).   Do I have to roll my own refresh token solution?

**Comment by marshallswain** [comment] 2017-03-23 18:40
@jamesholcomb You can either roll your own, or if you're on a low-traffic app, query the db in a hook and check that the user hasn't been blocked.  We will eventually release an official solution.

**Comment by johncrisostomo** [comment] 2017-03-23 21:16
@ekryski That's the reason why I also got confused. I checked the tokens generated under "when adding custom options" in `utils.test.js` and it's giving me a valid token. So I kind of know that the issue isn't on feathers-authentication alone, but with somewhere else. I'll look into it more this weekend as I am really curious as to what is causing it.

**Comment by asdacap** [comment] 2017-04-29 08:52
Hi there, I'm having the same issue. It seems to be caused by this line https://github.com/feathersjs/feathers-authentication/blob/master/src/socket/handler.js#L100 where it seems to wait for the token to expire and then log it out. This is actually quite useful for short token lifecycle (like several minutes) where we don't want the user to have access when the token already expired.

Unfortunately it seems that setTimeout will immediately run the callback when the timeout is too large. Probably because of this http://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values. I suggest using this https://www.npmjs.com/package/long-timeout or make some form of exception where in case the delay is very large, don't wait for expire time.

**Comment by marshallswain** [comment] 2017-05-03 14:15
@asdacap thanks for figuring that out.  Would you mind creating a PR with long-timeout?

**Comment by asdacap** [comment] 2017-05-08 07:16
Sorry for the late reply. Having issue figuring out a way to test it. Just created a pull request. Please review.

**Comment by ekryski** [comment] 2017-05-10 16:52
Looks to be closed by #499. Big round of applause for @asdacap. 👏

**Closed by ekryski** 2017-05-10 16:52 UTC
