### ISSUE TITLE
unique email not working while create

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers-authentication#572] opened 2017-09-17 17:58 UTC
Hi, for example I created a below code in my index.html

```js
var User = {
  email: 'admin@feathersjs.com',
  password: 'admin',
  permissions: ['*']
};

app.service('auth').create(User).then(user => {
  console.log('Created default user', user);
}).catch(console.error);
```

I don't know why but after each page refresh create is new user. My schema model look like below:

```js
module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const auth = new mongooseClient.Schema({
  
    email: { type: String, unique: true, dropDups: true, required : true },
    password: { type: String, required : true },
    permissions: { type: String },
  
  
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
  });

  return mongooseClient.model('auth', auth);
};
```

On the occasion why my collection name here is auth and after create an user is auths?

**Comment by daffl** [comment] 2017-09-17 19:23
What module versions are you using? Is there error messages?

**Comment by SeaDog505** [comment] 2017-09-18 06:33
I have feathes-cli version 2.3.7 any error message. Something is wrong because previously it was OK. Previously I created one user and next I received a message that the user exists. Now after each page refresh is create new user. Script not checks if user exists but after changed db.collection from auth on eg. users I can create only one user with the same email. The second time I receive a message: "email: admin@feathersjs.com" already exists."
I don't understand that. I dropped my collection and I dropped my DB. The problem is the same.

**Comment by daffl** [comment] 2017-09-18 15:47
We need an example application to look at and reproduce the problem.

**Comment by SeaDog505** [comment] 2017-09-19 11:06
I know what was a problem probably. I launched my application, then I refreshed a page and is created a new user. Then I had to remove db without stopped the application. In this moment I refreshed a page and each next refresh has been creating a new user without checks if user already exists. I don't stopped the app! I checks now and I see that when I drop db or collection and I stop app and it relaunch I can add only one the same user. Can you explain me why I have to stop app before db.dropDatabase()? Tell me too why my collection in schema is "auth" and in mongo I see "auths" while "auth" collection exists too but is some other data there.

**Comment by daffl** [comment] 2017-09-19 16:19
I think the `auth` vs. `auths` name is a mistake on your side. The generator will not change db or collection names. Dropping a database from under a running application without restarting it is always a case that can cause tons of issues.

**Comment by SeaDog505** [comment] 2017-09-20 11:35
I created new DB, then I launched this application. After launched the application in mongoDB I see that DB it was created and when I use this DB and I execute the command: show collection(); I see auths collection and system.indexes. I don't see auth collection but if I execute an command: db.auth.find({}); I receive this result:

> db.auth.find({});
2017-09-20T13:27:00.412+0200 TypeError: Object function () {
    var ex;
    try {
        this._authOrThrow.apply(this, arguments);
    } catch (ex) {
        print(ex);
        return 0;
    }
    return 1;
} has no method 'find'
> db.auths.find({});

I created too new application too and I have the same issue.

**Comment by daffl** [comment] 2017-09-21 15:27
As I mentioned before, without a reproducible example it is almost impossible for us to figure out what is happening here.

**Comment by SeaDog505** [comment] 2017-09-25 07:13
I understand, OK. Below is my config file:

{
  "host": "localhost",
  "port": 3030,
  "public": "../public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "authentication": {
    "secret": "My secret key",
    "strategies": [
      "jwt",
      "local"
    ],
    "path": "/authentication",
    "service": "auth",
    "jwt": {
      "header": {
        "type": "access"
      },
      "audience": "https://yourdomain.com",
      "subject": "anonymous",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "entity": "user",
      "usernameField": "email",
      "passwordField": "password"
    }
  },
  "mongodb": "mongodb://localhost:27017/MyDatabase"
}

I noticed, that after first launched application is created hidden auth collection. I can have empty index.html, js file, whatever. Does not matter. First launched my application is changed my collection while in my config is auth.

**Comment by teddest** [comment] 2017-09-27 00:01
I'm experiencing the same issue.

Here are the steps I took to reproduce scaffolding an app from scratch.

```
NodeJS v8.1.2
FeathersJS 2.3.3
RethinkDB 2.3.6

$ feathers generate app
? Accept defaults...

$ feathers generate authentication
? What authentication providers do you want to use? Other PassportJS strategies not in this list can
still be configured manually. Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? RethinkDB
? What is the database connection string? rethinkdb://localhost:28015/smart_garden

curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "feathers@example.com", "password": "secret" }'
curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "feathers@example.com", "password": "secret" }'
curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "feathers@example.com", "password": "secret" }'
curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "feathers@example.com", "password": "secret" }'
```
I verified that 4 documents were created with the same email and password.

**Comment by daffl** [comment] 2017-09-27 00:11
RethinkDB does not support unique constraints. You will have to check yourself in a `before` hook if the email already exists. This also applies to MongoDB (you have to add a unique constraint on the email).

I'm going to close this issue since there is not much more debugging we can do without a complete repository to reproduce the original problem.

**Closed by daffl** 2017-09-27 00:11 UTC

**Comment by SeaDog505** [comment] 2017-09-27 06:44
OK, Daff my problem had resolved previously. Now I wanted to understand why after first launched my application my collection name "auth" is changed on "auths" however the main question is other than my second question we can close this issue. We know that my problem was on me side. I not stopped the application. Regarding the second problem I named my authentication service like users (default) and everything is all right. I think the mongoDB has "auth" collection for authenticate their users therefore a collection name "auth" is changed on "auths". This is no matter already. Thanks for replies and the conversation.
